version: '3.9'

services:
  tiled:
    build:
      context: .
    container_name: tiled
    ports:
      - "5800:5800"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ./:/data
    environment:
      DISPLAY_WIDTH: 2300
      DISPLAY_HEIGHT: 1200
      APP_NAME: Tiled
  map:
    image: node:alpine
    container_name: map
    ports:
      - "3000:5173"
    volumes:
      - ./:/app
    user: 1000:1000
    working_dir: /app
    command: ash -c "npm install && npm run dev"